### ISSUE TITLE
Regions need updating

### ISSUE THREAD

**Issue by pc-mreeves** [srbartlett/awscosts#15]
If I get a moment I will try to add support for more regions.

We're missing:

- us-east-2
- ca-central-1
- ap-south-1
- ap-northeast-2
- eu-west-1
- eu-west-2

ref: http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region

**Comment by pc-mreeves** [comment]
Actually it looks like this fork has already done the work... https://github.com/chanakyad-cuelogic/awscosts

**Comment by srbartlett** [comment]
Sorry for the delay.  Pull requested merged.
