### ISSUE TITLE
EBS Pricing is wrong

### ISSUE THREAD

**Issue by lardcanoe** [srbartlett/awscosts#8]
The json file you are using has old pricing.

https://github.com/CloudHealth/awscosts/tree/switch_to_jsonp_source has changes to use the latest source. I'd be happy to get the branch into a state that it can be merged into yours.

Also have https://github.com/CloudHealth/awscosts/tree/ebs_optimized to pull in ebs_optimized pricing.

Let me know what you think...

**Comment by srbartlett** [comment]
It's been a while.... but since i was updating the Gem to support the new AWS Region 'Frankfurt' I pulled in your changes.  All pricing except 'emr' now uses JSON_P. Thanks guys.
